name: install/cache ruby tools

inputs:
  tools: { required: false, type: string }
  cache: { required: false, type: string, default: yes }
  key:   { required: false, type: string }

outputs:
  cache-hit:
    value: ${{ steps.update.outputs.cache-hit }}

runs:
  using: composite
  steps:

    - id: setup
      shell: bash
      run: |
        : setup use-ruby-tools
        given_key="${{ inputs.key }}"
        version_key="$( (ruby --version; gem --version) | (md5sum||md5) | awk '{print $1}' )"
        key="${given_key:+$given_key-}${version_key}"
        echo "::set-output name=command::gem install"
        echo "::set-output name=prefix::$(gem environment gemdir)"
        echo "::set-output name=key::$key"

    - id: update
      uses: office-tecoli/actions-install-and-cache@v0
      with:
        command:   ${{ steps.setup.outputs.command }}
        directory: ${{ steps.setup.outputs.prefix }}
        target:    ${{ inputs.tools }}
        cache:     ${{ inputs.cache }}
        key:       ${{ steps.setup.outputs.key }}
        sudo:      true
