name: setup tools

inputs:
  apt:    { required: false, type: string }
  brew:   { required: false, type: string }
  perl:   { required: false, type: string }
  python: { required: false, type: string }
  ruby:   { required: false, type: string }
  cache:  { required: false, type: string, default: yes }
  key:    { required: false, type: string }

outputs:
  apt-cache-hit:
    value: ${{ steps.apt.outputs.cache-hit }}
  brew-cache-hit:
    value: ${{ steps.brew.outputs.cache-hit }}
  perl-cache-hit:
    value: ${{ steps.perl.outputs.cache-hit }}
  python-cache-hit:
    value: ${{ steps.python.outputs.cache-hit }}
  ruby-cache-hit:
    value: ${{ steps.ruby.outputs.cache-hit }}

runs:
  using: composite
  steps:

    - id: apt
      if: inputs.apt != ''
      uses: office-tecoli/actions-use-apt-tools@v0
      with:
        tools: ${{ inputs.apt }}
        cache: ${{ inputs.cache }}
        key:   ${{ inputs.key }}

    - id: brew
      if: inputs.brew != ''
      uses: office-tecoli/actions-use-brew-tools@v0
      with:
        tools: ${{ inputs.brew }}
        cache: ${{ inputs.cache }}
        key:   ${{ inputs.key }}

    - id: perl
      if: inputs.perl != ''
      uses: office-tecoli/actions-use-perl-tools@v0
      with:
        tools: ${{ inputs.perl }}
        cache: ${{ inputs.cache }}
        key:   ${{ inputs.key }}

    - id: python
      if: inputs.python != ''
      uses: office-tecoli/actions-use-python-tools@v0
      with:
        tools: ${{ inputs.python }}
        cache: ${{ inputs.cache }}
        key:   ${{ inputs.key }}

    - id: ruby
      if: inputs.ruby != ''
      uses: office-tecoli/actions-use-ruby-tools@v0
      with:
        tools: ${{ inputs.ruby }}
        cache: ${{ inputs.cache }}
        key:   ${{ inputs.key }}
