name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:

  initial:
    strategy:
      matrix:
        os:
          - os: ubuntu-latest
            tools:  apt
#            tools:  apt perl python
            apt:    bmake
#            perl:   App::ansiecho
#            python: legit
#          - os: macos-latest
#            tools:  brew perl python
#            brew:   rcs
#            perl:   App::ansiecho
#            python: legit
    runs-on: ${{ matrix.os.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache:  workflow
          apt:    ${{ matrix.os.apt }}
#          brew:   ${{ matrix.os.brew }}
#          perl:   ${{ matrix.os.perl }}
#          python: ${{ matrix.os.python }}
      - run: (cd __test__; ./run.sh ${{ matrix.os.tools }})
      - run: |
          : check cache-hit
          for tool in ${{ matrix.os.tools }}
          do
            case $tool in
              apt)    test "${{ steps.action.outputs.apt-cache-hit }}"    != true ;;
              brew)   test "${{ steps.action.outputs.brew-cache-hit }}"   != true ;;
              perl)   test "${{ steps.action.outputs.perl-cache-hit }}"   != true ;;
              python) test "${{ steps.action.outputs.python-cache-hit }}" != true ;;
            esac
          done

  cached:
    needs: initial
    strategy:
      matrix:
        os:
          - os: ubuntu-latest
            tools:  apt
#            tools:  apt perl python
            apt:    bmake
#            perl:   App::ansiecho
#            python: legit
#          - os: macos-latest
#            tools:  brew perl python
#            brew:   rcs
#            perl:   App::ansiecho
#            python: legit
    runs-on: ${{ matrix.os.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache:  workflow
          apt:    ${{ matrix.os.apt }}
#          brew:   ${{ matrix.os.brew }}
#          perl:   ${{ matrix.os.perl }}
#          python: ${{ matrix.os.python }}
      - run: (cd __test__; ./run.sh ${{ matrix.os.tools }})
      - run: |
          : check cache-hit
          for tool in ${{ matrix.os.tools }}
          do
            case $tool in
              apt)    test "${{ steps.action.outputs.apt-cache-hit }}"    == true ;;
              brew)   test "${{ steps.action.outputs.brew-cache-hit }}"   == true ;;
              perl)   test "${{ steps.action.outputs.perl-cache-hit }}"   == true ;;
              python) test "${{ steps.action.outputs.python-cache-hit }}" == true ;;
            esac
          done
